### PR TITLE
passed components props to the wizard so any props passed to react wi…

### PR DESCRIPTION
**Pull request by Asher978**
# content of this PR

-  [x] Passed props to the main wizard component
-  [x] result of which will be having any props passed to the `wizard` available in all steps

### CODE REVIEW

**Comment by EINazare** [comment]
Hello there @Asher978 ,

Thank you for your interest in working with our products and for this PR.
I'll take a look at it on our next update.

Best,
Manu

**Comment by EINazare** [comment]
Hello again, @Asher978 ,

Just took a look at your PR and from what I understand you are sending all the Wizard Component props, to each of the steps.
Not sure how this is helpful, I am inclined to decline this PR and think of a way, to send the props from the component in which you render our wizard.

Best,
Manu

**Comment by Asher978** [comment]
Hi Tim, 

The idea was to have the steps access the props that are being passed to the wizard component. I see your point of passing the entire props object to all the steps, which may seem unnecessary in your point of view, however in my case I have redux in place and there is quite a large amount of data coming from redux state that needs to be passed to the steps. If I put that data to the `wizardData` prop, it does not update automatically as the redux states updates since the wizardData is held in the state of the wizard component. I am submitting another PR and hoping that this solution is ok in your opinion and can be accepted.

**Comment by EINazare** [comment]
Just made an update, and added stepProps for each of the steps. Hope this is what you were looking for.

Best,
Manu

**Pull request closed without merging**
